/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrolebancario.View;

import java.util.Date;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.swing.JOptionPane;
import sistemacontrolebancario.Model.Dao.ContaCorrenteDao;
import sistemacontrolebancario.Model.Dao.ContaDao;
import sistemacontrolebancario.Model.Dao.ContaPoupancaDao;
import sistemacontrolebancario.Model.Dominio.Conta;
import sistemacontrolebancario.Model.Dominio.ContaCorrente;
import sistemacontrolebancario.Model.Dominio.ContaPoupanca;

/**
 *
 * @author Ranna Lys
 */
public class CadastroGUI extends javax.swing.JFrame {
    TelaInicialGUI telaInicial;
    /**
     * Creates new form CadastroGUI
     */
    public CadastroGUI() {
        this.telaInicial = new TelaInicialGUI();
        initComponents();
        comboBoxTipoConta.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelNumeroConta = new javax.swing.JLabel();
        labelNumeroAgencia = new javax.swing.JLabel();
        labelTitular = new javax.swing.JLabel();
        comboBoxTipoConta = new javax.swing.JComboBox<>();
        labelTipoConta = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labelLimite = new javax.swing.JLabel();
        textFieldNumeroConta = new javax.swing.JFormattedTextField();
        textFieldNumeroAgencia = new javax.swing.JFormattedTextField();
        textFieldTitular = new javax.swing.JTextField();
        spinnerLimite = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        labelCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCadastro.setText("Cadastrar Conta Bancária");

        labelNumeroConta.setText("Número da Conta:");

        labelNumeroAgencia.setText("Número da Agência:");

        labelTitular.setText("Nome do Titular:");

        comboBoxTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Poupança" }));
        comboBoxTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoContaActionPerformed(evt);
            }
        });

        labelTipoConta.setText("Tipo de Conta:");

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        labelLimite.setText("Limite Especial:");

        try {
            textFieldNumeroConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textFieldNumeroConta.setToolTipText("Este campo deve conter exatamente 5 dígitos.");
        textFieldNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroContaActionPerformed(evt);
            }
        });

        try {
            textFieldNumeroAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textFieldNumeroAgencia.setToolTipText("Este campo deve conter exatamente 5 dígitos.");
        textFieldNumeroAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroAgenciaActionPerformed(evt);
            }
        });

        spinnerLimite.setModel(new javax.swing.SpinnerNumberModel(10.0d, 0.0d, 1000.0d, 10.0d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumeroConta)
                                    .addComponent(labelTitular)
                                    .addComponent(labelTipoConta)
                                    .addComponent(labelNumeroAgencia)
                                    .addComponent(labelLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNumeroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroConta)
                    .addComponent(textFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroAgencia)
                    .addComponent(textFieldNumeroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitular)
                    .addComponent(textFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoConta)
                    .addComponent(comboBoxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLimite)
                    .addComponent(spinnerLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonVoltar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoContaActionPerformed
        if(comboBoxTipoConta.getSelectedItem().equals("Conta Poupança")){
            spinnerLimite.setEnabled(false);
        }else{
            spinnerLimite.setEnabled(true);
        }
    }//GEN-LAST:event_comboBoxTipoContaActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        String agencia = textFieldNumeroAgencia.getText();
        String numeroConta = textFieldNumeroConta.getText();
        String titular = textFieldTitular.getText();
        Double limite = (Double) spinnerLimite.getValue();
        Date data = new Date();
        
        ContaDao busca = new ContaDao();
        Conta c = busca.findConta(numeroConta, agencia);
        
        if(!"".equals(agencia) && !"".equals(numeroConta) && !"".equals(titular) && limite!=null){
            if(comboBoxTipoConta.getSelectedItem().equals("Conta Corrente")){
                ContaCorrente conta = new ContaCorrente();

                conta.setAgencia(agencia);
                conta.setNumero(numeroConta);
                conta.setTitular(titular);
                conta.setDataAbertura(data);
                conta.setLimite(limite);

                ContaDao dao = new ContaDao();
                
                if(c == null){
                    dao.create(conta);
                    
                    JOptionPane.showMessageDialog(
                        null,
                        comboBoxTipoConta.getSelectedItem().toString() + 
                        " cadastrada com sucesso!"
                    );
                }else{
                    JOptionPane.showMessageDialog(null, "Esta conta já existe");
                }
            }else{
                ContaPoupanca conta = new ContaPoupanca();

                conta.setAgencia(agencia);
                conta.setNumero(numeroConta);
                conta.setTitular(titular);
                conta.setDataAbertura(data);

                ContaDao dao = new ContaDao();
                
                if(c == null){
                    dao.create(conta);
                    JOptionPane.showMessageDialog(
                        null,
                        comboBoxTipoConta.getSelectedItem().toString() + 
                        " cadastrada com sucesso!"
                    );
                }else{
                    JOptionPane.showMessageDialog(null, "Esta conta já existe");
                }
            }

            limparCampos();

            telaInicial.show();

            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos corretamente.");
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        telaInicial.show();
        
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void textFieldNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroContaActionPerformed
        
    }//GEN-LAST:event_textFieldNumeroContaActionPerformed

    private void textFieldNumeroAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumeroAgenciaActionPerformed
    
    public void limparCampos(){
        textFieldNumeroAgencia.setText("");
        textFieldNumeroConta.setText("");
        textFieldTitular.setText("");
        spinnerLimite.setValue(10);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JComboBox<String> comboBoxTipoConta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelLimite;
    private javax.swing.JLabel labelNumeroAgencia;
    private javax.swing.JLabel labelNumeroConta;
    private javax.swing.JLabel labelTipoConta;
    private javax.swing.JLabel labelTitular;
    private javax.swing.JSpinner spinnerLimite;
    private javax.swing.JFormattedTextField textFieldNumeroAgencia;
    private javax.swing.JFormattedTextField textFieldNumeroConta;
    private javax.swing.JTextField textFieldTitular;
    // End of variables declaration//GEN-END:variables
}
