/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrolebancario.View;

import javax.swing.JOptionPane;
import sistemacontrolebancario.Model.Bo.OperacoesBancarias;
import sistemacontrolebancario.Model.Dao.ContaDao;
import sistemacontrolebancario.Model.Dominio.ContaCorrente;
import sistemacontrolebancario.Model.Dominio.ContaPoupanca;

/**
 *
 * @author Ranna Lys
 */
public class SaqueGUI extends javax.swing.JFrame {
    private String tipoConta;
    private ContaCorrente contaCorrente;
    private  ContaPoupanca contaPoupanca;
    /**
     * Creates new form SaqueGUI
     */
    public SaqueGUI(ContaCorrente conta) {
        initComponents();
        this.tipoConta = "CC";
        this.contaCorrente = conta;
        labelResuldadoSaqueMaximo.setText("R$ " + String.valueOf(conta.getSaldo()+conta.getLimite()));
        labelResultadoSaldo.setText("R$ " + String.valueOf(conta.getSaldo()));
        labelSaqueMaximo.setText("Saque Máximo + Limite Espec.");
    }
    
    public SaqueGUI(ContaPoupanca conta) {
        initComponents();
        this.tipoConta = "CP";
        this.contaPoupanca = conta;
        labelResuldadoSaqueMaximo.setText(String.valueOf(conta.getSaldo()));
        labelResultadoSaldo.setText("R$ " + String.valueOf(conta.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        spinnerValor = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        buttonSacar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelSaqueMaximo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelResuldadoSaqueMaximo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelResultadoSaldo = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Operação de Saque");

        jLabel2.setText("Valor:");

        spinnerValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10000.0d, 10.0d));
        spinnerValor.setToolTipText("Limite máximo de saque: R$ 10.000,00");

        buttonSacar.setText("Sacar");
        buttonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSacarActionPerformed(evt);
            }
        });

        jLabel3.setText("Saque mínimo:");

        labelSaqueMaximo.setText("Saque máximo:");

        jLabel5.setText("R$ 20,00");

        labelResuldadoSaqueMaximo.setText("######");

        jLabel6.setText("Saldo Atual:");

        labelResultadoSaldo.setText("######");

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(230, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(buttonSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSaqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelResuldadoSaqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelResultadoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResultadoSaldo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaqueMaximo)
                    .addComponent(labelResuldadoSaqueMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSacarActionPerformed
        OperacoesBancarias operacoes = new OperacoesBancarias();
        OperacoesBancariasGUI operacoesGui;

        Double valorSaque = (Double) spinnerValor.getValue();

        if(getTipoConta().equals("CC")){
            if(valorSaque <= (contaCorrente.getSaldo() + contaCorrente.getLimite())){
                if(operacoes.sacarLimiteEspecial(contaCorrente, valorSaque)){
                    ContaDao dao = new ContaDao();
                    dao.update(contaCorrente);

                    operacoesGui = new OperacoesBancariasGUI(contaCorrente);
                    operacoesGui.show();

                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao sacar.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao sacar no limite especial.");
            }
        }else{
            if(operacoes.sacar(contaPoupanca, valorSaque)){
                ContaDao dao = new ContaDao();
                dao.update(contaPoupanca);

                operacoesGui = new OperacoesBancariasGUI(contaPoupanca);
                operacoesGui.show();

                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao sacar.");
            }
        }
    }//GEN-LAST:event_buttonSacarActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        OperacoesBancariasGUI operacoesGui;

        if(getTipoConta().equals("CC")){
            operacoesGui = new OperacoesBancariasGUI(contaCorrente);
            operacoesGui.show();

            dispose();
        }else{
            operacoesGui = new OperacoesBancariasGUI(contaPoupanca);
            operacoesGui.show();

            dispose();
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    public String getTipoConta() {
        return tipoConta;
    }

    public void setTipoConta(String tipoConta) {
        this.tipoConta = tipoConta;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSacar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelResuldadoSaqueMaximo;
    private javax.swing.JLabel labelResultadoSaldo;
    private javax.swing.JLabel labelSaqueMaximo;
    private javax.swing.JSpinner spinnerValor;
    // End of variables declaration//GEN-END:variables
}
