/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrolebancario.View;

import javax.swing.JOptionPane;
import sistemacontrolebancario.Model.Bo.OperacoesBancarias;
import sistemacontrolebancario.Model.Dao.ContaDao;
import sistemacontrolebancario.Model.Dominio.Conta;
import sistemacontrolebancario.Model.Dominio.ContaCorrente;
import sistemacontrolebancario.Model.Dominio.ContaPoupanca;

/**
 *
 * @author Ranna Lys
 */
public class TransferenciaGUI extends javax.swing.JFrame {
    private String tipoConta;
    private ContaCorrente contaCorrente;
    private  ContaPoupanca contaPoupanca;
    /**
     * Creates new form TransferenciaGUI
     */
    public TransferenciaGUI(ContaCorrente conta) {
        initComponents();
        this.tipoConta = "CC";
        this.contaCorrente = conta;
        labelresultadoSaldo.setText("R$ " + String.valueOf(conta.getSaldo()));
    }
    
    public TransferenciaGUI(ContaPoupanca conta) {
        initComponents();
        this.tipoConta = "CP";
        this.contaPoupanca = conta;
        labelresultadoSaldo.setText("R$ " + String.valueOf(conta.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldNumeroAgencia = new javax.swing.JFormattedTextField();
        textFieldNumeroConta = new javax.swing.JFormattedTextField();
        labelresultadoSaldo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        spinnerValor = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        buttonTransferir = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Operação de Transferência");

        jLabel2.setText("Saldo Atual:");

        jLabel3.setText("Número da Agência:");

        jLabel4.setText("Número da Conta:");

        try {
            textFieldNumeroAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textFieldNumeroAgencia.setToolTipText("Este campo deve conter exatamente 5 dígitos.");
        textFieldNumeroAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroAgenciaActionPerformed(evt);
            }
        });

        try {
            textFieldNumeroConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textFieldNumeroConta.setToolTipText("Este campo deve conter exatamente 5 dígitos.");
        textFieldNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroContaActionPerformed(evt);
            }
        });

        labelresultadoSaldo.setText("##################");

        jLabel5.setText("Valor");

        spinnerValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10000.0d, 10.0d));
        spinnerValor.setToolTipText("Limite máximo de saque: R$ 10.000,00");

        buttonTransferir.setText("Transferir");
        buttonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferirActionPerformed(evt);
            }
        });

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelresultadoSaldo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNumeroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelresultadoSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNumeroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNumeroAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumeroAgenciaActionPerformed

    private void textFieldNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumeroContaActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        OperacoesBancariasGUI operacoesGui;

        if(getTipoConta().equals("CC")){
            operacoesGui = new OperacoesBancariasGUI(contaCorrente);
            operacoesGui.show();

            dispose();
        }else{
            operacoesGui = new OperacoesBancariasGUI(contaPoupanca);
            operacoesGui.show();

            dispose();
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferirActionPerformed
        OperacoesBancarias operacoes = new OperacoesBancarias();
        OperacoesBancariasGUI operacoesGui;

        Double valorTranferencia = (Double) spinnerValor.getValue();
        
        String numeroAgencia = textFieldNumeroAgencia.getText();
        String numeroConta = textFieldNumeroConta.getText();
        
        ContaDao busca = new ContaDao();
        Conta conta = busca.findConta(numeroConta, numeroAgencia);
        
        if(conta != null){
            if(getTipoConta().equals("CC")){
                if(operacoes.transferir(contaCorrente, conta, valorTranferencia)){
                    ContaDao dao = new ContaDao();
                    dao.update(contaCorrente);
                    dao.update(conta);

                    operacoesGui = new OperacoesBancariasGUI(contaCorrente);
                    operacoesGui.show();

                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao transferir.");
                }
            }else{
                if(operacoes.transferir(contaPoupanca, conta, valorTranferencia)){
                    ContaDao dao = new ContaDao();
                    dao.update(contaPoupanca);
                    dao.update(conta);
                    
                    operacoesGui = new OperacoesBancariasGUI(contaPoupanca);
                    operacoesGui.show();

                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao transferir.");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "A conta para qual o valor está sendo transferido não existe.");
        }
    }//GEN-LAST:event_buttonTransferirActionPerformed

    public String getTipoConta() {
        return tipoConta;
    }

    public void setTipoConta(String tipoConta) {
        this.tipoConta = tipoConta;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTransferir;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelresultadoSaldo;
    private javax.swing.JSpinner spinnerValor;
    private javax.swing.JFormattedTextField textFieldNumeroAgencia;
    private javax.swing.JFormattedTextField textFieldNumeroConta;
    // End of variables declaration//GEN-END:variables
}
